FROM golang:1.20.0-buster

RUN mkdir -p /go/src
WORKDIR /go/src

COPY src /go/src
RUN go mod tidy

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /go/src/app/queue/main /go/src/app/queue/main.go